### ISSUE TITLE
Shard muss auf den Boden droppen! (Bleibt in der Luft hängen)

### ISSUE THREAD

**Issue by kikoplg** [Totenfluch/Herobrine#16]

**Comment by Totenfluch** [comment]
Sollte nun auf dem Boden spawnen außer der Spieler war in dem Moment am springen. Das mach ich später noch.

**Comment by kikoplg** [comment]
"außer der Spieler war in dem Moment am springen" 
-> Sollte noch gemacht werden!

**Comment by kikoplg** [comment]
wie oben gesagt.
