### ISSUE TITLE
Kompass für Shards

### ISSUE THREAD

**Issue by kikoplg** [Totenfluch/Herobrine#24]

**Comment by kikoplg** [comment]
Sollte so ein kleiner Hud sein, schön gestalten mit Farben.
Centred Box mit Kompass, in der Box steht:

Zeile1: Klasse zB. Spy oder Bomber
Zeile 2+3 Kompass zur Shard
Zeile 4: Shardstatus: "0/3 Shard" usw.

**Comment by Totenfluch** [comment]
Ist geschrieben ; muss getestet werden

**Comment by kikoplg** [comment]
done
