### ISSUE TITLE
Store-Items

### ISSUE THREAD

**Issue by kikoplg** [Totenfluch/Herobrine#47]
Sollte doch möglich sein die Store-Items Skins/Masks/Trails/Aura/usw. am Herobrine unsichtbar zu machen? Also wenn man HB wird automatisch alles unsichtbar machen.

**Comment by Totenfluch** [comment]
Nicht ohne jedes store Modul einzeln zu ändern

**Comment by kikoplg** [comment]
Ok. Also nicht möglich :P.
