### ISSUE TITLE
Shard gibt instant dmg wenn ein Spieler mit dem shard stirbt und ein anderer den shard aufnimmt.

### ISSUE THREAD

**Issue by kikoplg** [Totenfluch/Herobrine#6]
Shard gibt instant dmg wenn ein Spieler mit dem shard stirbt und ein anderer den shard aufnimmt.

**Comment by Totenfluch** [comment]
Sollte gelöst sein, muss jedoch nochmal getestet werden

**Comment by Totenfluch** [comment]
scheint gefixt zu sein
