### ISSUE TITLE
Man muss ausstellen das man in T joinen kann oder man keinen Bos joinen kann.

### ISSUE THREAD

**Issue by kikoplg** [Totenfluch/Herobrine#8]
Man muss ausstellen das man in T joinen kann oder man keinen Bos joinen kann.

**Comment by Totenfluch** [comment]
> bot_controllable 0

in die Server cfg / gamemode cfg

**Comment by kikoplg** [comment]
funktioniert leider nicht!

**Comment by Totenfluch** [comment]
hm schlecht.

Spieler werden jetzt gekickt wenn diese einem Bot joinen ... ich such nach einer besseren Lösung
